export const CONFIG_LOADED = 'CONFIG_LOADED';
export const GENRES_LOADED = 'GENRES_LOADED';
export const MOVIES_LOADED = 'MOVIES_LOADED';
export const SET_MIN_RATING = 'SET_MIN_RATING';
export const FILTER_GENRES = 'FILTER_GENRES';